config/routes.rb
Rails.application.routes.draw do
  resources :trashes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "cases#index"

  get "about", controller: "static", action: "about"

  resources :dimensions do
    resources :categories
    post "enqueue_category_suggestions", action: "enqueue_category_suggestions"
  end

  resources :annotations
  resources :codebooks
  resources :questions
  resources :responses
  resources :statistics
  resources :themes
  resources :searches

  resources :cases do
    post "enqueue_keywords", action: "enqueue_keywords"
  end


end

app/models/question.rb
# A Question is a representation of a survey question.
# This class provides convenience methods for navigating question keys and labels, as well as selecting topical subsets of questions.
# For now, Questions are hardcoded and not persisted.
class Question < ApplicationRecord

  has_many :responses
  belongs_to :dimension

  def self.experience_questions
    Question.where(is_experience: true)
  end

  def self.identity_questions
    Question.where(is_identity: true)
  end

  def self.reflection_questions
    Question.where(is_reflection: true)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @responses = @question.responses.order(:case_id)

    question_ids = Question.all.pluck(:id)
    previous_index = (question_ids.index(@question.id) - 1)
    next_index = (question_ids.index(@question.id) + 1) % question_ids.length
    @previous_question_id = question_ids[previous_index]
    @next_question_id = question_ids[next_index]

  end

  private

  def scope_nav
    @nav_context = "responses"
  end

end

app/views/questions/_form.html.erb
<%= turbo_frame_tag "#{question.key}_#{response.id}" do %>
	<% if success %>
		<% @css_class = success ? "form-success" : "form-error" %>
	<% end %>
	<%= form_with model: response, data: { turbo_frame: "#{question.key}_#{response.id}" } do |f| %>
		<% response.raw_codes.try(:sort).each do |code| %>
			<div class="tag"><%= code %></div>
		<% end %>
		<%= f.text_area question.field, value: response.raw_codes.try(:sort).try(:join, ', '), multiple: true, class: "#{@css_class}" %>
		<%= f.submit "Save", class: "small" %>
	<% end %>
<% end %>

app/views/questions/index.html.erb
<%- title "Codebook" %>

<h1>Explore Responses.</h1>
<ul class="breadcrumbs">
  <li><a href="/">Home</a> /</li>
  <li>Responses</li>
</ul>

<ul class="list">
  <% @questions.each do |question| %>
    <li>
      <%= link_to question.label, question_path(question.id) %>
    </li>
  <% end %>
</ul>

app/views/questions/show.html.erb
<%- title "Participant Survey Responses to #{@question.label} Question" %>

<h1><%= @responses.count %> Participant Survey Responses to "<%= @question.label %>".</h1>
<ul class="breadcrumbs">
  <li><a href="/">Home</a> /</li>
  <li><%= link_to "Responses", questions_path %> /</li>
  <li><%= @question.label %></li>
</ul>

<% if @previous_question_id %>
  <%= link_to "<", question_path(@previous_question_id), class: "flip", id: "flip-left" %>
<% end %>
<% if @next_question_id %>
  <%= link_to ">", question_path(@next_question_id), class: "flip", id: "flip-right" %>
<% end %>

<p>These are the responses provided by participants to the "<%= @question.label %>" question. Blank responses are not listed here. Click on a code to show all survey participant responses related to that code. You may select multiple codes to further filter the responses.</p>

<p>For a complete list of codes for this question, refer to the <%= link_to "codebook.", codebook_path(@question.id), class: "jump-link" %></p>

<table>
  <thead>
    <tr>
      <th>Participant Survey Response</th>
      <th>Answer</th>
      <th><%= link_to "Codes", codebook_path(@question.key), class: "jump-link-light" %></th>
    </tr>
  </thead>
  <tbody>
    <% counter = 0 %>
    <% @responses.each do |response| %>
      <% alt = counter % 2 == 1 ? "" : "alt" %>
      <% counter += 1 %>
      <% next unless response.value.present? %>
      <tr class="<%= alt %> data-row" data-codes="<%= response.raw_codes %>">
        <td class="label">
        <%= link_to response.case_id, case_path(response.case_id), class: "jump-link" %>
        </td>
        <td class="response">
          <%= response.value %>
        </td>
        <td class="form-entry">
          <% if @question.is_affinity || @question.is_reflection %>
            —
          <% else %>
            <%= render "/responses/form", response: response, success: nil, filters: true %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script language="javascript">

  function toggleIconControls(codeID) {
    const icons = Array.from(document.getElementsByClassName('tag-icon-control'))

    icons.forEach(element => {
      if (element.getAttribute('data-code') == codeID) {
        if (Array.from(element.classList).includes('hidden')) {
          element.classList.remove('hidden');
        } else {
          element.classList.add('hidden');
        }
      }
    });
  }

  function filterBy(codeID) {

    const dataRows = Array.from(document.getElementsByClassName('data-row'));
    const codeElements = Array.from(document.getElementsByClassName('codes'));

    codeElements.forEach(element => {
      if (element.getAttribute('data-code') == codeID) {
        if (Array.from(element.classList).includes('active')) {
          // If a code is already marked active, and is clicked on again, clear it.
          element.classList.remove('active');
        } else {
          element.classList.add('active');
        }
      }
    });

    var activeCodes = Array.from(document.querySelectorAll(".codes.active"));

    if (activeCodes.length == 0) {
      dataRows.forEach(rowElement => {
        rowElement.classList.remove('hidden');
      });
    } else {
      dataRows.forEach(rowElement => {
        rowElement.classList.add('hidden');
      });
    }

    activeCodes.forEach(codeElement => {
      let codeId = codeElement.getAttribute('data-code');
      dataRows.forEach(rowElement => {
        let codes = JSON.parse(rowElement.getAttribute('data-codes'));
        if (codes.includes(codeId)) {
          rowElement.classList.remove('hidden');
        }
      });
    });

  }

</script>