config/routes.rb
Rails.application.routes.draw do
  resources :trashes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "cases#index"

  get "about", controller: "static", action: "about"

  resources :dimensions do
    resources :categories
    post "enqueue_category_suggestions", action: "enqueue_category_suggestions"
  end

  resources :annotations
  resources :codebooks
  resources :questions
  resources :responses
  resources :statistics
  resources :themes
  resources :searches

  resources :cases do
    post "enqueue_keywords", action: "enqueue_keywords"
  end


end

app/models/dimension.rb
# A Dimension reflects a demographic category.
class Dimension < ApplicationRecord

  validates_presence_of :name
  validates_presence_of :display_name
  validates_uniqueness_of :name

  has_many :questions

  def categories
    @categories ||= Category.where(dimension: self.name).order(:name)
  end

  def codes
    @codes ||= Code.where(dimension: self.name).order(:name)
  end

  def suggest_categories
    update_attribute(:suggested_categories, [])
    categories = Services::SuggestCategories.perform(self.id).map{|category| category['category'] }
    update_attribute(:suggested_categories, categories)
  end

end

app/controllers/dimensions_controller.rb
class DimensionsController < ApplicationController

  before_action :scope_dimension

  def index
    @dimensions = Dimension.all.order(:display_name)
  end

  def show
    @categories = @dimension.categories
    @codes = @dimension.codes
    @enqueued_at = params[:enqueued_at].present? ? Time.at(params[:enqueued_at].to_i).strftime("%T %Z") : nil
    @isEditMode = params[:is_edit_mode] == "true"

    dimension_ids = Dimension.all.order(:display_name).pluck(:id)
    previous_index = (dimension_ids.index(@dimension.id) - 1)
    next_index = (dimension_ids.index(@dimension.id) + 1) % dimension_ids.length
    @previous_dimension_id = dimension_ids[previous_index]
    @next_dimension_id = dimension_ids[next_index]
  end

  def enqueue_category_suggestions
    CategorySuggestionsJob.perform_async(params[:dimension_id])
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("frame-suggestions", partial: "/dimensions/suggestions", locals: { dimension: @dimension, enqueued: params[:enqueued] })
      end
    end
  end

  private

  def scope_dimension
    @dimension = params[:id].present? ? Dimension.find(params[:id]) : Dimension.new
  end

  def scope_nav
    @nav_context = "categories"
  end

end

app/views/dimensions/_suggestions.html.erb
<%= turbo_frame_tag "frame-suggestions" do %>

  <% if enqueued && (dimension.suggestions_updated_at.nil? || DateTime.parse(enqueued) > dimension.suggestions_updated_at) %>
    <div class="throbber"><div></div><div></div></div>
    <script language="javascript">
      function refreshSpinner() {
        setInterval(() => {
          location.reload();
        }, 3000);
      }
      refreshSpinner();
    </script>
  <% else %>
    <ul>
      <% dimension.suggested_categories.each do |suggestion| %>
        <li><%= suggestion %></li>
      <% end %>
    </ul>
    <%= button_to "Get Suggestions", dimension_enqueue_category_suggestions_path(dimension.id, params: { enqueued: DateTime.now }, method: :put, form: { data: { turbo: true, turbo_stream: true } } ) %>
  <% end %>

<% end %>

app/views/dimensions/index.html.erb
<%- title "Categories" %>

<h1>Explore Categories by Identity Dimension.</h1>
<ul class="breadcrumbs">
  <li><a href="/">Home</a> /</li>
  <li>Categories</li>
</ul>

<ul class="list">
  <% @dimensions.each do |dimension| %>
    <li>
      <%= link_to dimension.display_name, dimension_path(dimension) %>
    </li>
  <% end %>
</ul>

app/views/dimensions/show.html.erb
<%- title "#{@dimension.display_name} Categories" %>

<% if @previous_dimension_id %>
  <%= link_to "<", dimension_path(id: @previous_dimension_id), class: "flip", id: "flip-left" %>
<% end %>
<% if @next_dimension_id %>
  <%= link_to ">", dimension_path(id: @next_dimension_id), class: "flip", id: "flip-right" %>
<% end %>

<% if @isEditMode %>
  <h1>Manage "<%= @dimension.display_name %>" Categories.</h1>
  <ul class="breadcrumbs">
    <li><a href="/">Home</a> /</li>
    <li><%= link_to "Categories", dimensions_path %> /</li>
    <li><%= link_to @dimension.display_name, dimension_path(@dimension) %> /</li>
    <li>Manage</li>
  </ul>

  <h2>Select a Category to Edit:</h2>
  <div class="tag-collection">
    <% @categories.each do |category| %>
      <%= link_to dimension_category_path(dimension_id: @dimension.id, id: category.id) do %>
        <div class="tag edit-link-light category"><%= category.name %></div>
      <% end %>
    <% end %>
    <%= link_to new_dimension_category_path(dimension_id: @dimension.id) do %>
      <div class="tag-button">New Category</div>
    <% end %>
  </div>
<% else %>
  <h1>"<%= @dimension.display_name %>" Categories.</h1>
  <ul class="breadcrumbs">
    <li><a href="/">Home</a> /</li>
    <li><%= link_to "Categories", dimensions_path %> /</li>
    <li><%= @dimension.display_name %></li>
  </ul>

  <h2>Select Categories to Compare:</h2>
  <div class="tag-collection">
    <div class="tag zoom-link-light category" onclick="filterBy('uncategorized');" id="category-uncategorized" data-category="uncategorized">Uncategorized Codes</div>
    <% @categories.each do |category| %>
      <div class="tag zoom-link-light category" onclick="filterBy('<%= category.id %>');" id="category-<%= category.id %>" data-category="<%= category.id %>"><%= category.name %></div>
    <% end %>
    <%= link_to dimension_path(@dimension, is_edit_mode: "true") do %>
      <div class="tag-button">Manage Categories</div>
    <% end %>
  </div>
<% end %>

<% if @isEditMode %>
  <h2>Suggested Categories:</h2>
  <%= render partial: "suggestions", locals: { dimension: @dimension, enqueued: nil } %>
<% else %>
  <h2>Associated Codes:</h2>
  <p>Codes belonging to the selected categories are displayed below.</p>
  <div class="tag-collection">
    <% @codes.each do |code| %>
      <% categories = code.categories.map(&:id) %>
      <div class="tag codes" id="<%= code.id %>" data-code="<%= code.id %>" data-categories="<%= categories.any? ? categories : ["uncategorized"] %>">
        <%= code.name %>
      </div>
    <% end %>
  </div>
<% end %>

<%= render partial: "/shared/filtering" %>