config/routes.rb
Rails.application.routes.draw do
  resources :trashes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "cases#index"

  get "about", controller: "static", action: "about"

  resources :dimensions do
    resources :categories
    post "enqueue_category_suggestions", action: "enqueue_category_suggestions"
  end

  resources :annotations
  resources :codebooks
  resources :questions
  resources :responses
  resources :statistics
  resources :themes
  resources :searches

  resources :cases do
    post "enqueue_keywords", action: "enqueue_keywords"
  end


end

app/models/theme.rb
# A Theme is a label representing a fundamental concept that emerges from the data, in particular clusters of one or more Codes.
class Theme
  include ActiveGraph::Node

  property :name
  property :description
  property :notes
  
  before_validation :sanitize

  validates :name, presence: true
  validates_uniqueness_of :name

  has_many :out, :categories, rel_class: :EmergesFrom

  private

  def sanitize
    self.name.strip!
  end

end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  def index
    @themes = Theme.all.order(:name)
  end

  def new
    @theme = Theme.new
  end

  def show
    @dimensions = Dimension.all.order(:name)
    @theme = Theme.find(params[:id])
    @categories = Category.all

    theme_ids = Theme.all.order(:name).pluck(:id)
    previous_index = (theme_ids.index(@theme.id) - 1)
    next_index = (theme_ids.index(@theme.id) + 1) % theme_ids.length
    @previous_theme_id = theme_ids[previous_index]
    @next_theme_id = theme_ids[next_index]

  end

  def create
    @theme = Theme.new(theme_params)
    success = @theme.save
    redirect_to @theme
  end

  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy
    redirect_to themes_path
  end

  def update
    @theme = Theme.find(params[:id])
    new_category_ids = theme_params[:categories].split(/[\,\s]/)
    update_kind = @theme.categories.length == new_category_ids.length ? "metadata" : "category"

    if theme_params[:categories]
      categories = Category.where(id: new_category_ids)
      @theme.categories = categories
    end

    @theme.name = theme_params[:name]
    @theme.description = theme_params[:description]
    @theme.notes = theme_params[:notes]
    update_kind ||= "metadata"
    success = @theme.save

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("frame-theme", partial: "/themes/form", locals: { theme: @theme, success: success, update_kind: update_kind })
      end
    end
  end

  private

  def theme_params
    params.require(:theme).permit(:name, :description, :notes, :categories)
  end

  def scope_nav
    @nav_context = "themes"
  end

end

app/views/themes/_form.html.erb
<%= turbo_frame_tag "frame-theme" do %>
	<%= form_with model: theme, id: "form-theme", class: "form-theme", data: { turbo_frame: "theme" } do |f| %>
		<% css_class = success ? "form-success" : "form-error" %>
		<fieldset>
			<%= label :name, "Name" %>
			<%= f.text_field :name, class: update_kind == "metadata" ? css_class : "" %>
		</fieldset>
		<div class="two-column">
			<div class="column">
				<fieldset>
					<%= label :description, "Description" %>
					<%= f.text_area :description, class: update_kind == "metadata" ? css_class : ""  %>
				</fieldset>
			</div>
			<div class="column">
				<fieldset>
					<%= label :notes, "Notes" %>
					<%= f.text_area :notes, class: update_kind == "metadata" ? css_class : ""  %>
				</fieldset>
			</div>
		</div>
		<%= f.hidden_field :categories, id: "field-categories", value: theme.categories.map(&:id) %>
		<%= f.submit "Update", id: "button-theme" %>
  <% end %>
<% end %>

app/views/themes/index.html.erb
<%- title "Themes" %>

<h1>Explore Themes.</h1>
<ul class="breadcrumbs">
  <li><a href="/">Home</a> /</li>
  <li>Themes</li>
</ul>

<div class="tag-collection" style="margin-top: 1rem;">
  <% @themes.each do |theme| %>
      <%= link_to theme_path(theme.id) do %>
        <div class="tag zoom-link-light"><%= theme.name %></div>
      <% end %>
  <% end %>
  <%= link_to new_theme_path do %>
    <div class="tag-button">New Theme</div>
  <% end %>
</div>

app/views/themes/new.html.erb
<%- title "New Theme" %>

<h1>Add a Theme</h1>
<ul class="breadcrumbs">
  <li><a href="/">Home</a> /</li>
  <li><%= link_to "Themes", themes_path %> /</li>
  <li>New</li>
</ul>

<%= form_with model: @theme do |f| %>
  <fieldset>
  <%= label :name, "Name" %>
  <%= f.text_field :name %>
  </fieldset>
  <fieldset>
  <%= label :description, "Description" %>
  <%= f.text_area :description  %>
  </fieldset>
  <fieldset>
  <%= label :notes, "Notes" %>
  <%= f.text_area :notes  %>
  </fieldset>
  <%= f.submit "Create" %>
<% end %>

app/views/themes/show.html.erb
<%- title "Themes" %>

<h1>"<%= @theme.name %>" Theme.</h1>
<ul class="breadcrumbs">
  <li><a href="/">Home</a> /</li>
  <li><%= link_to "Themes", themes_path %> /</li>
  <li><%= @theme.name %></li>
</ul>

<% if @previous_theme_id %>
  <%= link_to "<", theme_path(id: @previous_theme_id), class: "flip", id: "flip-left" %>
<% end %>
<% if @next_theme_id %>
  <%= link_to ">", theme_path(id: @next_theme_id), class: "flip", id: "flip-right" %>
<% end %>

<%= render partial: "form", locals: { theme: @theme, success: nil, update_kind: nil } %>

<h2>Categories</h2>
<p>Categories related to this theme are are highlighted in black below. Click to add or remove a category from this theme. Changes are saved automatically.</p>

<% @dimensions.each do |dimension| %>
  <% dimension_categories = dimension.categories %>
  <% if dimension_categories.any? %>
    <h3><%= link_to dimension.display_name, dimension_path(id: dimension.id), class: "jump-link" %></h3>

    <div class="tag-collection">
      <% dimension_categories.sort_by(&:name).each do |category| %>
        <% is_selected = @theme.categories.include? category %>
        <a onclick="filterBy('<%= category.id %>'); updateAssociatedCategories(); return false">
          <div class="tag category <%= is_selected ? 'active' : '' %>" id="category-<%= category.id %>" data-category="<%= category.id %>">
            <%= category.name %>
          </div>
        </a>
      <% end %>
    </div>
  <% end %>
<% end %>

<h2>Danger Zone</h2>
<%= button_to "Delete This Theme", theme_path(@theme), form: { data: { turbo_confirm: "Are you sure you want to delete this Theme? This action cannot be undone." } }, method: :delete %>

<%= render partial: "/shared/filtering" %>

<script language="javascript">

  function toggleThemeForm(themeID) {
    const themeElement = document.getElementById('theme-' + themeID);
    const newThemeFormElement = document.getElementById('new-theme-form');
    const themeForm = document.getElementById('form-theme-' + themeID);

    if (Array.from(themeElement.classList).includes('active')) {
      newThemeFormElement.classList.add('hidden');
      themeForm.classList.remove('hidden');
    } else {
      newThemeFormElement.classList.remove('hidden');
      themeForm.classList.add('hidden');
    }
  }

  function updateAssociatedCategories() {
    const activeCategories = Array.from(document.querySelectorAll(".category.active"));
    categoryIDs = activeCategories.map((element) => element.getAttribute('data-category'));
    document.getElementById("field-categories").value = categoryIDs;
    submitButton = document.getElementById("button-theme");
    submitButton.click();
  }

</script>