config/routes.rb
Rails.application.routes.draw do
  resources :trashes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "cases#index"

  get "about", controller: "static", action: "about"

  resources :dimensions do
    resources :categories
    post "enqueue_category_suggestions", action: "enqueue_category_suggestions"
  end

  resources :annotations
  resources :codebooks
  resources :questions
  resources :responses
  resources :statistics
  resources :themes
  resources :searches

  resources :cases do
    post "enqueue_keywords", action: "enqueue_keywords"
  end


end

app/models/category.rb
# A Category is a label applied to a group of related Codes within a provided dimension.
# For example, a category may refer to a subset of the codes related to "age".
# Categories are machine-derived. As such, they are influenced by biases in external training data.
# Careful human discernment of categories is required to identify and address these biases.
class Category

  include ActiveGraph::Node

  property :name
  property :dimension
  property :description

  validates :name, presence: true
  validates :dimension, presence: true
  validates_uniqueness_of :name, scope: :dimension

  has_many :out, :codes, rel_class: :Contains
  has_many :in, :themes, rel_class: :EmergesFrom

  # Generates a hash with the unique category name as the key and the count of its associated codes as a value.
  def self.histogram(dimension)
    categories = where(dimension: dimension).query_as(:c).with('c, count{(c)-[:CONTAINS]-(code:Code)} AS ct').return("c.name, ct").order('ct DESC')
    categories.inject({}) {|accumulator,category| accumulator[category.values[0]] ||= 0; accumulator[category.values[0]] += category.values[1]; accumulator}
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :scope_dimension

  def show
    @category = Category.find(params[:id])
    @codes = Code.where(dimension: @category.dimension).order(:name)
    @dimension = Dimension.find_by(name: @category.dimension)

    category_ids = Category.where(dimension: @category.dimension).pluck(:id)
    previous_index = (category_ids.index(@category.id) - 1)
    next_index = (category_ids.index(@category.id) + 1) % category_ids.length
    @previous_category_id = category_ids[previous_index]
    @next_category_id = category_ids[next_index]
  end

  def new
    @category  = Category.new(name: "New Category", dimension: @dimension.name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to dimension_category_path(@dimension, @category)
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to dimension_path(@dimension)
  end

  def update
    @category = Category.find(params[:id])
    new_code_ids = category_params[:codes].split(/[\,\s]/)
    update_kind = @category.codes.length == new_code_ids.length ? "metadata" : "category"

    if category_params[:codes]
      codes = Code.where(id: new_code_ids)
      @category.codes = codes
    end

    @category.name = category_params[:name]
    @category.description = category_params[:description]
    update_kind ||= "metadata"
    success = @category.save

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("frame-category", partial: "/categories/form", locals: { category: @category, dimension: @dimension, success: success, update_kind: update_kind })
      end
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :description, :dimension, :codes)
  end

  def scope_dimension
    @dimension = params[:dimension_id].present? ? Dimension.find(params[:dimension_id]) : Dimension.new
  end

  def scope_nav
    @nav_context = "categories"
  end

end

app/views/categories/_form.html.erb
<%= turbo_frame_tag "frame-category" do %>
	<%= form_with model: category, id: "form-category", url: dimension_category_path(dimension, category ), class: "", data: { turbo_frame: "category" } do |f| %>
		<% css_class = success ? "form-success" : "form-error" %>
		<fieldset>
			<%= label :name, "Name" %>
			<%= f.text_field :name, class: update_kind == "metadata" ? css_class : "" %>
		</fieldset>
		<fieldset>
			<%= label :description, "Description" %>
			<%= f.text_area :description, class: update_kind == "metadata" ? css_class : ""  %>
		</fieldset>
		<%= f.hidden_field :codes, id: "field-codes", value: category.codes.map(&:id) %>
		<%= f.submit "Update", id: "button-category" %>
  <% end %>
<% end %>

app/views/categories/_suggestions.html.erb
<%= turbo_frame_tag "frame-suggestions" do %>

  <% if enqueued && (context.suggestions_updated_at.nil? || DateTime.parse(enqueued) > context.suggestions_updated_at) %>
    <div class="throbber"><div></div><div></div></div>
    <script language="javascript">
      function refreshSpinner() {
        setInterval(() => {
          location.reload();
        }, 3000);
      }
      refreshSpinner();
    </script>
  <% else %>
    <ul class="columnar-list">
      <% context.suggested_categories.each do |suggestion| %>
        <li><%= suggestion %></li>
      <% end %>
    </ul>
    <%= button_to "Get Suggestions", codebook_enqueue_category_suggestions_path(question.id, params: { enqueued: DateTime.now }, method: :put, form: { data: { turbo: true, turbo_stream: true } } ) %>
  <% end %>

<% end %>

app/views/categories/edit.html.erb
<%- title "Categories" %>

<h1>Category: "<%= @category.name %>"</h1>

<%= render partial: "form", locals: { category: @category, success: nil, update_kind: nil } %>

<p><%= link_to "More categories", categories_path(context: @context) %></p>

<h2>Codes</h2>
<p>Codes associated with this category are are highlighted in black below. Click to add or remove a code from this category. Changes are saved automatically.</p>

<div class="tag-collection">
  <% @codes.each do |code| %>
    <% is_selected = @category.codes.include? code %>
    <a onclick="updateAssociatedCodes('<%= code.id %>'); return false">
      <div class="tag codes <%= is_selected ? 'active' : '' %>" id="<%= code.id %>" data-code="<%= code.id %>">
        <%= code.name %>
      </div>
    </a>
  <% end %>
</div>


<h2>Danger Zone</h2>
<%= button_to "Delete This Category", category_path(@category), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete %>

<%= render partial: "/shared/filtering" %>

<script language="javascript">

  function updateAssociatedCodes(codeID) {
    const codeElement = document.getElementById(codeID);
    if (Array.from(codeElement.classList).includes("active")) {
      codeElement.classList.remove("active")
    } else {
      codeElement.classList.add("active")
    }
    const activeCodes = Array.from(document.querySelectorAll(".codes.active"));
    codeIDs = activeCodes.map((element) => element.getAttribute('data-code'));
    document.getElementById("field-codes").value = codeIDs;
    submitButton = document.getElementById("button-category");
    submitButton.click();
  }

</script>

app/views/categories/index.html.erb
<%- title "#{@section_name} Codebook Categories" %>

<h1>Explore categories for "<%= @section_name %>".</h1>
<p>You can <%= link_to "find more categories", categories_path(action: :by_context) %>, <%= link_to "go to the codebook", codebook_path(@question.id) %>, or <%= link_to "move on to themes", themes_path %>.</p>

<% if @isEditMode %>
  <h2>Select a Category to Edit:</h2>
  <div class="tag-collection">
    <% @categories.each do |category| %>
      <%= link_to question_category_path(question_id: @question.id, id: category.id) do %>
        <div class="tag edit-link-light category"><%= category.name %></div>
      <% end %>
    <% end %>
    <%= link_to new_question_category_path(question_id: @question.id) do %>
      <div class="tag-button">New Category</div>
    <% end %>
    <%= link_to question_categories_path(question_id: @question.id) do %>
      <div class="tag-button">Compare Categories</div>
    <% end %>
  </div>
<% else %>
  <h2>Select Categories to Compare:</h2>
  <div class="tag-collection">
    <div class="tag zoom-link-light category" onclick="filterBy('uncategorized');" id="category-uncategorized" data-category="uncategorized">Uncategorized Codes</div>
    <% @categories.each do |category| %>
      <div class="tag zoom-link-light category" onclick="filterBy('<%= category.id %>');" id="category-<%= category.id %>" data-category="<%= category.id %>"><%= category.name %></div>
    <% end %>
    <%= link_to question_categories_path(question_id: @question.id, is_edit_mode: "true") do %>
      <div class="tag-button">Edit Categories</div>
    <% end %>
  </div>
<% end %>

<% if @isEditMode %>
  <h2>Suggested Categories:</h2>
  <%= render partial: "suggestions", locals: { context: @context, question: @question, enqueued: nil } %>
<% else %>
  <h2>Associated Codes:</h2>
  <p>Codes belonging to the selected categories are displayed below.</p>
  <div class="tag-collection">
    <% @codes.each do |code| %>
      <% categories = code.categories.map(&:id) %>
      <div class="tag codes" id="<%= code.id %>" data-code="<%= code.id %>" data-categories="<%= categories.any? ? categories : ["uncategorized"] %>">
        <%= code.name %>
      </div>
    <% end %>
  </div>
<% end %>

<%= render partial: "/shared/filtering" %>

app/views/categories/new.html.erb
<%- title "New Categpory" %>

<h1>Add a Category</h1>
<ul class="breadcrumbs">
  <li><a href="/">Home</a> /</li>
  <li><%= link_to "Categories", dimensions_path %> /</li>
  <li>New</li>
</ul>

<div class="two-column">

  <div class="column">
    <%= form_with model: @category, url: dimension_categories_path(dimension_id: @dimension.id) do |f| %>
      <fieldset>
      <%= label :name, "Name" %>
      <%= f.text_field :name %>
      </fieldset>
      <fieldset>
      <%= label :description, "Description" %>
      <%= f.text_area :description  %>
      </fieldset>
      <%= f.hidden_field :dimension %>
      <%= f.submit "Create" %>
    <% end %>
  </div>

  <% if @dimension.suggested_categories.any? %>
    <div class="column">
      <h2>Suggested categories:</h2>
      <ul>
        <% @dimension.suggested_categories.each do |suggestion| %>
          <li><%= suggestion %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

</div>

app/views/categories/show.html.erb
<%- title "Categories: #{@category.name}" %>

<h1>Category: "<%= @category.name %>"</h1>
<ul class="breadcrumbs">
  <li><a href="/">Home</a> /</li>
  <li><%= link_to "Categories", dimensions_path %> /</li>
  <li><%= link_to @dimension.display_name, dimension_path(@dimension) %> /</li>
  <li><%= @category.name %></li>
</ul>

<% if @previous_category_id %>
  <%= link_to "<", dimension_category_path(dimension_id: @dimension.id, id: @previous_category_id), class: "flip", id: "flip-left" %>
<% end %>
<% if @next_category_id %>
  <%= link_to ">", dimension_category_path(dimension_id: @dimension. id, id: @next_category_id), class: "flip", id: "flip-right" %>
<% end %>

<%= render partial: "form", locals: { category: @category, dimension: @dimension, success: nil, update_kind: nil } %>

<% if @category.id.present? %>
  <h2>Codes</h2>
  <p>Codes associated with this category are are highlighted in black below. Click to add or remove a code from this category. Changes are saved automatically.</p>

  <div class="tag-collection">
    <% @codes.each do |code| %>
      <% is_selected = @category.codes.include? code %>
      <a onclick="updateAssociatedCodes('<%= code.id %>'); return false">
        <div class="tag codes <%= is_selected ? 'active' : '' %>" id="<%= code.id %>" data-code="<%= code.id %>">
          <%= code.name %>
        </div>
      </a>
    <% end %>
  </div>
<% end %>

<% if @category.id.present? %>
  <h2>Danger Zone</h2>
  <%= button_to "Delete This Category", dimension_category_path(dimension_id: @dimension.id, category_id: @category.id), form: { data: { turbo_confirm: "Are you sure you want to delete this Category? This action cannot be undone." } }, method: :delete %>
<% end %>

<%= render partial: "/shared/filtering" %>

<script language="javascript">

  function updateAssociatedCodes(codeID) {
    const codeElement = document.getElementById(codeID);
    if (Array.from(codeElement.classList).includes("active")) {
      codeElement.classList.remove("active")
    } else {
      codeElement.classList.add("active")
    }
    const activeCodes = Array.from(document.querySelectorAll(".codes.active"));
    codeIDs = activeCodes.map((element) => element.getAttribute('data-code'));
    document.getElementById("field-codes").value = codeIDs;
    submitButton = document.getElementById("button-category");
    submitButton.click();
  }

</script>